source/getting-started/tutorials/blink/index.md

Fix broken link to `cmd_blink` code

Fix broken link in blink tutorial

---

source/getting-started/tutorials/hw-commands/index.md

Move the LED Danger Warning in [docs.amdc.dev/getting-started/tutorials/hw-commands](url) so that it comes before the instructions.

Move LED Warning

---

source/firmware/xilinx-tools/building-and-running-firmware.md

The `Building and Running Firmware` instructions currently does not have the users add the `app_cpu0` project when following the `Private User Applications` pathway. This fixes #18. 
This PR updates the Building and Running Firmware` instructions to resolve this. (@npetersen2, have I correctly understood the intended workflow in these instructions?))

Add app_cpu0 to building and running firmware instructions

---

source/firmware/xilinx-tools/create-user-app.md

The instructions to create a new user app refer to the `bare` project, which is a relic from the AMDC's single core days. This PR updates the instructions to refer to the `app_cpu1` project instead of `bare`.

Update create user app instructions for dual core

---

source/getting-started/tutorials/vsi/index.md

The source code for the VSI tutorial has several small problems with the include paths and a misnamed function. This PR fixes these issues.
Further, the PR clarifies the instructions at the end of the tutorial, informing the user that they should read the [Create Custom User App](https://docs.amdc.dev/firmware/xilinx-tools/create-user-app.html) document and that they need to add a compiler define to enable their new app.

VSI tutorial fixes

---

source/getting-started/user-guide/code-profiling.md

This PR fixes a type-o in the Code Profiling doc.

Fix small type-o in code profiling doc

---

source/getting-started/user-guide/logging/buffered.md

Fix a small type-o in `buffered.md`

Fix type-o in buffered logging doc

---

source/getting-started/tutorials/vsi/index.md

Fixes #35 
Update ctrl `init` and `deinit` commands so that they turn on/off the pwm interface. 
This is done by calling `pwm_enable()` and `pwm_disable()` within the `init` and `deinit` command function. This means that if the PWM interface is already enabled (i.e. via `hw pwm on`) when someone issues a `ctrl init` command, the user will receive a failure notification. Likewise if someone issues `ctrl deinit`, but the PWM interface has been previously disabled (`hw pwm off`) the user will receive a failure response. This may be confusing... but I think it is an acceptable implementation and consistent with how `hw pwm on` and `hw pwm off` are implemented.

Make vsi tutorial to turn on/off pwm interface

---

source/getting-started/user-guide/logging/streaming.md

This PR implements #43 by adding instructions on how to get interactive plots working in Jupyter Lab (the current instructions only apply to Jupyter Notebook).

Update streaming log instructions for Jupyter Lab

---

source/getting-started/user-guide/host-interface/python-wrapper.md

This PR adds an `Attention` callout to the [Python Wrapper doc](https://docs.amdc.dev/getting-started/user-guide/host-interface/python-wrapper.html#python-wrapper) that helps users debug issues with the `AMDC.py` module.

Add alert to prevent AMDC.py issues

---

source/firmware/xilinx-tools/building-and-running-firmware.md

This PR adds a user alert regarding the choice of folder for establishing a private AMDC repository. Some of the configuration settings that we establish in SDK cause `.project` and `.cproject` to have absolute file system paths. This can cause problems when editting a private user repo across multiple computers.

Add hint on choice of repo folder

---

source/getting-started/user-guide/host-interface/python-wrapper.md

As part of the review for PR #55, @npetersen2 made three improvement suggestions for the `Attention` callout in the [Python Wrapper doc](https://docs.amdc.dev/getting-started/user-guide/host-interface/python-wrapper.html). This PR implements two of these suggestions:
1. Clarify that `conda install...` is an example of how to install `pyserial`
2. Use `pathlib` to add the `scripts` folder to the system path in an OS-agnostic manner. 
This PR also improves the typesetting of the repository structure and example code within the callout.

Improve Python Wrapper Attention Callout Regarding Import AMDC

---

source/getting-started/user-guide/logging/buffered.md

Change outdated syntax of UART comm port initialization in order to compile the example code.

Update com port initialization in buffered logging copy-paste example.

---

source/firmware/arch/index.md

The [Examples section of the Firmware Architecture](https://docs.amdc.dev/firmware/arch/index.html#examples) page links to the `blink` app. This link is out of date (it corresponds to the old, single-core architecture). This PR is to fix the broken link by pointing to the `blink` app's new location in the dual core architecture.

Fix broken link to blink app

---

source/getting-started/user-guide/injection/index.rst

Three changes:
1. Fix a type-o (missing word `can`)
2. Explicitly indicate inclusion of `sys/injection.h` header file
3. Add hint to enable the injection module in `user_config.h` (I helped a couple students stuck on this last week)
I built the html on my PC and everything looked fine.

Edit and update injection documentation

---

source/firmware/arch/images/block-diagram.svg
source/firmware/arch/index.md

Replace the old block diagram with a new one that reflects the current state of the firmware architecture.
Notable changes:
- Show that one core runs `lwIP` and one core runs user code
- Show communication mechanisms between hardware resources
- `On-Chip Memory` between ARM cores
- `AXI4` between FPGA and ARM core
I rendered the new page locally and it looks good.

Update firmware architecture block diagram

---

source/firmware/xilinx-tools/building-and-running-firmware.md
source/getting-started/user-guide/logging/index.md

I added 2 fixes for SDK issues I found when working with dual-cores on an AMDC RevD. At the end I also added solutions for copying files between Xilinx projects as Xilinx doesn't seem to correctly import files built in other projects. Finally, I fixed a typo ([here](https://docs.amdc.dev/getting-started/user-guide/logging/index.html#python-interface)). I switched "scipts" to "scripts". I built this html file on my computer and it seems to work well.

Building and Running Firmware Additions

---

source/getting-started/user-guide/amds-interface.md

This PR updates the AMDS interface section of the AMDC platform documentation. In the documentation it says the outputs `V` and `C` when using `counters` command  should be non-zero if the connection is active, but `C` is corrupt flag and it is zero. Additional details regarding the usage of `counters` command is also added

Update in AMDS command line interface section

---

source/conf.py
source/firmware/xilinx-tools/building-and-running-firmware.md
source/getting-started/tutorials/custom-control-rate/index.md
source/getting-started/tutorials/index.md
source/getting-started/tutorials/profiling-tasks/index.md
source/getting-started/user-guide/index.md
source/getting-started/user-guide/task-profiling.md

This tutorial explains how to configure the AMDC to run control code at any frequency (e.g., 100 kHz).
It also discusses how to take fine grain timing measurements using log variables and the `drv/cpu_timer` module.
This was created to answer @DivyaMendpara's questions.

Add new tutorial on custom control rate config

---

source/accessories/amds/sensor-cards/index.md
source/accessories/uinverter/index.md
source/hardware/index.md

This information is sprinkled around the docs. Now, it is clearly stated in tables.
I rendered locally and believe the formatting looks good.

Add spec tables from IEMDC paper

---

source/getting-started/tutorials/profiling-tasks/index.md

Per a question, clarify when to enable task stats in the task init function.
i.e., AFTER calling the `scheduler_init()` function

Clarify when to enable task stats

---

source/firmware/xilinx-tools/installing-xilinx-tools.md

This PR updates the AMDC document for the section of Installing Xilinx Tools. Updated document is available in [installing-xilinx-tools.md](https://github.com/Severson-Group/docs.amdc.dev/blob/user/noguchi-takahiro/update-document/source/firmware/xilinx-tools/installing-xilinx-tools.md).
The following change is taking place since the WebPACK installer is currently not available:
- In the Downloading installation executable section, the link of “Vivado HLx 2019.1: WebPACK and Editions - Windows Self Extracting Web Installer” was changed to be "Vivado HLx 2019.1: All OS installer Single-File Download".
- The sentence about an installation size was changed from 8GB to be 21.39GB.
Based on this, I have conducted BLINK tutorial with new grad students and have verified that this change of the …

Update the link to the Xilinx installer

---

source/accessories/amds/mainboard/index.md
source/getting-started/user-guide/amds-interface/index.md

This PR:
1. fixes AMDS SPI pinout labels to close #111
2. adds documentation to indicate which version of the AMDS firmware should be used with which version of the AMDC firmware to close [AMDS issue 51](https://github.com/Severson-Group/AMDS/issues/51)

AMDS documentation tweaks

---

source/firmware/development/index.md

This PR fixes a spelling error in the development page of the AMDC docs.
https://github.com/Severson-Group/docs.amdc.dev/blob/c2fe46d9da1d903bd18f4045828558974f195835/source/firmware/development/index.md#L52
##
This PR closes #122

Typo in development page

---

source/getting-started/user-guide/task-profiling.md

This PR closes #71 
An attention box message is added to inform users that the `scheduler_tcb_init()` function overrides `task_enable_stats()`.

Update task profile docs

---

.github/workflows/sphinx-build.yml

Closes #131
I updated us to `24.04`, because that is the latest supported version listed [here](https://github.com/actions/runner-images). Alternatively, we could just use `ubuntu-latest`, but that seems dangerous -- we could get blindsided by an incompatibility introduced down the road.

Update GitHub workflow to use Ubuntu 24.04

---

source/getting-started/tutorials/timing-manager/index.md

Fix typo in timing & sensors tutorial
